In [ ]:
#find the cholesky factorization for the matrix
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, ]])
print(la.cholesky(A))


[[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]]


In [ ]:
#find the cholesky factorization for the matrix
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
A = np.array([[1, -1, 0], [-1, 5, 0], [0, 0, 7]])
print(la.cholesky(A))


[[ 1.         -1.          0.        ]
 [ 0.          2.          0.        ]
 [ 0.          0.          2.64575131]]


In [ ]:
#find the LU factorization of the matrix
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
A = np.array([[1, 0], [-2, 1]])
B = np.array([[-2, 1], [-6, 4]])
C = np.array([[3, 0, 1], [6, 1, 1], [-3, 1, 0]])
D = np.array([[2, 0, 0], [0, -3, 1], [10, 12, 3]])

print(la.lu_factor(A))
print(la.lu_factor(B))
print(la.lu_factor(C))
print(la.lu_factor(D))


(array([[-2. ,  1. ],
       [-0.5,  0.5]]), array([1, 1], dtype=int32))
(array([[-6.        ,  4.        ],
       [ 0.33333333, -0.33333333]]), array([1, 1], dtype=int32))
(array([[ 6.        ,  1.        ,  1.        ],
       [-0.5       ,  1.5       ,  0.5       ],
       [ 0.5       , -0.33333333,  0.66666667]]), array([1, 2, 2], dtype=int32))
(array([[10. , 12. ,  3. ],
       [ 0. , -3. ,  1. ],
       [ 0.2,  0.8, -1.4]]), array([2, 1, 2], dtype=int32))


In [ ]:
#find the rank of the matrix
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

A = np.array([[2, 3, 1], [0, -1, 2], [0, 0, 3]])
B = np.array([[-2, 2, -3], [2, 1, -6], [-1, -2, 0]])
rank = np.array([np.linalg.matrix_rank(A), np.linalg.matrix_rank(B)])
print(rank)

[3 3]


In [ ]:
#find the eigenvalues and eigenvectors of the matrix and plot them
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la


a=np.array([[2,3,1], [0,-1,2], [0,0,3]])
w,v= np.linalg.eig(a)
print("E-value:")
print(w)
print("E-vector")
print(v)


E-value:
[ 2. -1.  3.]
E-vector
[[ 1.         -0.70710678  0.91287093]
 [ 0.          0.70710678  0.18257419]
 [ 0.          0.          0.36514837]]


In [ ]:
#find the eigenvalues and eigenvectors of the matrix and plot them
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la


a = np.array([[-2, 2, -3], [2, 1, -6], [-1, -2, 0]])
w, v = np.linalg.eig(a)
print("E-value:")
print(w)
print("E-vector")
print(v)


E-value:
[-3.  5. -3.]
E-vector
[[-0.95257934  0.40824829 -0.04912436]
 [ 0.27216553  0.81649658  0.838526  ]
 [-0.13608276 -0.40824829  0.54264255]]


In [ ]:
import numpy as np
A = np.array([[3,3,5], [3,5,9], [5,9,17]])
B = np.array([1,2,4])
x = np.linalg.solve(A, B)
print(x)

[-2.66453526e-16 -5.00000000e-01  5.00000000e-01]


In [ ]:
import numpy as np
A = np.array([[1, 2, -1], [2, -2, -2], [-1, 3, 4]])
B = np.array([-7, 8, 8])
x = np.linalg.solve(A, B)
print(x)


[ 6.77777778 -3.66666667  6.44444444]


In [ ]:
import numpy as np
A = np.array([[2, 1, 2], [-1, 2, -3], [3, 2, -1]])
B = np.array([6, 0, 6])
x = np.linalg.solve(A, B)
print(x)


[1. 2. 1.]


In [ ]:
import numpy as np
A = np.array([[2, 3, 5], [3, 5, 9], [5, 9, 13]])
B = np.array([4, 7, 17])
x = np.linalg.solve(A, B)
print(x)


[-3.  5. -1.]
