
```
Rank of a matrix

The rank of the matrix refers to the number of linearly independent rows or columns in the matrix. ρ(A) is used to denote the rank of matrix A. A matrix is said to be of rank zero when all of its elements become zero. The rank of the matrix is the dimension of the vector space obtained by its columns.
```

In [42]:
import numpy as np
A = np.array([[1, 2, 1], [1, -2, 3], [3, -7, 4]])
b = np. array([8, 1, 10])


In [43]:
sol = np. linalg.solve(A, b)
rank = np.linalg.matrix_rank(A)
inverse = np.linalg.inv(A)



In [44]:
from pandas import *

A1 = np.array([[1, -1, 2], [1, 2, -1], [0, 2, -2]])
AB = np.array([[1, -1, 2, 3], [1, 2, -1, -3], [0,2. -2,1]], dtype=object)
A2 = np.array([[1, 5, 7], [2, 3, 6], [4, 3, 6]])
b = np.array([4, 10, 12])
sol = np.linalg.solve(A2, b)
print(DataFrame(A1))
print(DataFrame(AB))
print(DataFrame(A2))

print(sol)



   0  1  2
0  1 -1  2
1  1  2 -1
2  0  2 -2
                0
0   [1, -1, 2, 3]
1  [1, 2, -1, -3]
2     [0, 0.0, 1]
   0  1  2
0  1  5  7
1  2  3  6
2  4  3  6
[ 1.         -4.22222222  3.44444444]


In [45]:
ra = np.linalg.matrix_rank(A1)
rab = np.linalg.matrix_rank(A)
print(ra)
print(rab)


2
3


In [46]:
print(f'Solution of the matrix is ', sol)
print(f'Rank of the matrix is ', rank)
print(f'The inverse of the matrix is ', inverse)


Solution of the matrix is  [ 1.         -4.22222222  3.44444444]
Rank of the matrix is  3
The inverse of the matrix is  [[ 0.59090909 -0.68181818  0.36363636]
 [ 0.22727273  0.04545455 -0.09090909]
 [-0.04545455  0.59090909 -0.18181818]]


In [47]:
a = np. array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
c = np.matmul(a, b)
print(c)


[[4 1]
 [2 2]]


Scipy  Stuff

In [52]:
import scipy.linalg as la
a = np.array([[0, 1, 1], [1, 2, 1], [3, 9, 8]])
(P, L, U) = la.lu(a)
DataFrame(P)
DataFrame(L)
DataFrame(U)



0    1         2
0  3.0  9.0  8.000000
1  0.0 -1.0 -1.666667
2  0.0  0.0 -0.666667